"""Spark SQL DDL Schema definitions for Raw layer (hive.raw_credit_risk)."""

RAW_DB_NAME = "raw_credit_risk"
RAW_HDFS_BASE = "/raw/credit_risk"

RAW_APPLICATION_TRAIN_DDL = f"""
CREATE TABLE IF NOT EXISTS {RAW_DB_NAME}.raw_application_train
USING PARQUET
LOCATION '{RAW_HDFS_BASE}/application_train'
"""

RAW_APPLICATION_TEST_DDL = f"""
CREATE TABLE IF NOT EXISTS {RAW_DB_NAME}.raw_application_test
USING PARQUET
LOCATION '{RAW_HDFS_BASE}/application_test'
"""

RAW_BUREAU_DDL = f"""
CREATE TABLE IF NOT EXISTS {RAW_DB_NAME}.raw_bureau
USING PARQUET
LOCATION '{RAW_HDFS_BASE}/bureau'
"""

RAW_BUREAU_BALANCE_DDL = f"""
CREATE TABLE IF NOT EXISTS {RAW_DB_NAME}.raw_bureau_balance
USING PARQUET
LOCATION '{RAW_HDFS_BASE}/bureau_balance'
"""

RAW_POS_CASH_BALANCE_DDL = f"""
CREATE TABLE IF NOT EXISTS {RAW_DB_NAME}.raw_pos_cash_balance
USING PARQUET
LOCATION '{RAW_HDFS_BASE}/pos_cash_balance'
"""

RAW_CREDIT_CARD_BALANCE_DDL = f"""
CREATE TABLE IF NOT EXISTS {RAW_DB_NAME}.raw_credit_card_balance
USING PARQUET
LOCATION '{RAW_HDFS_BASE}/credit_card_balance'
"""

RAW_PREVIOUS_APPLICATION_DDL = f"""
CREATE TABLE IF NOT EXISTS {RAW_DB_NAME}.raw_previous_application
USING PARQUET
LOCATION '{RAW_HDFS_BASE}/previous_application'
"""

RAW_INSTALLMENTS_PAYMENTS_DDL = f"""
CREATE TABLE IF NOT EXISTS {RAW_DB_NAME}.raw_installments_payments
USING PARQUET
LOCATION '{RAW_HDFS_BASE}/installments_payments'
"""

RAW_ALL_DDLS = [
    RAW_APPLICATION_TRAIN_DDL,
    RAW_APPLICATION_TEST_DDL,
    RAW_BUREAU_DDL,
    RAW_BUREAU_BALANCE_DDL,
    RAW_POS_CASH_BALANCE_DDL,
    RAW_CREDIT_CARD_BALANCE_DDL,
    RAW_PREVIOUS_APPLICATION_DDL,
    RAW_INSTALLMENTS_PAYMENTS_DDL,
]
